# Generated by Django 4.2.27 on 2025-12-15 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journalyear_year_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalnumber',
            name='number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journalyear',
            name='year',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1995, message="Son 1995 dan kichik bo'lishi mumkin emas."), django.core.validators.MaxValueValidator(2100, message="Son 2100 dan katta bo'lishi mumkin emas.")]),
        ),
    ]
