# Generated by Django 4.2.27 on 2025-12-15 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_journalnumber_number_alter_journalyear_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalnumber',
            name='number',
            field=models.PositiveBigIntegerField(default=1, help_text="Jurnal soni (1 dan 10 gacha) bo'lishi kerak.", validators=[django.core.validators.MinValueValidator(1, message="Son 1 dan kichik bo'lishi mumkin emas."), django.core.validators.MaxValueValidator(10, message="Son 10 dan katta bo'lishi mumkin emas.")]),
        ),
        migrations.AlterField(
            model_name='journalyear',
            name='year',
            field=models.PositiveBigIntegerField(default=2000, help_text="Jurnal sonining yili (1995 dan 2100 gacha) bo'lishi kerak.", validators=[django.core.validators.MinValueValidator(1995, message="Son 1995 dan kichik bo'lishi mumkin emas."), django.core.validators.MaxValueValidator(2100, message="Son 2100 dan katta bo'lishi mumkin emas.")]),
        ),
    ]
