# Generated by Django 4.2.27 on 2025-12-17 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_journalnumber_number_alter_journalyear_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.journalnumber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.journalyear'),
            preserve_default=False,
        ),
    ]
