# Generated by Django 4.2.27 on 2025-12-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_reviewerarticle_is_resubmit_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=100)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address', 'attempted_at'], name='user_app_lo_ip_addr_61b22e_idx'), models.Index(fields=['username', 'attempted_at'], name='user_app_lo_usernam_33ef66_idx')],
            },
        ),
    ]
